[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/feed.ics"
  to = "/.netlify/functions/ical"
  status = 200

[[redirects]]
  from = "/feed.json"
  to = "/.netlify/functions/json"
  status = 200

[[redirects]]
  from = "/api/sync"
  to = "/.netlify/functions/sync"
  status = 200
